### ISSUE TITLE
Nodaba doesn't go to hub

### ISSUE THREAD

**Issue by IHateMyKite** [kurotatsu77/UnforgivingSkyrim#3]
Found a strange bug. For some reason, after the quest where player eats concentrated black goo in front of Nodaba and escape the devices, she will not go to huh. Looking at the details in console shows up that the relevant package is running (more in screenshot)
![package](https://github.com/kurotatsu77/UnforgivingSkyrim/assets/103142567/e8175ad6-ba8b-4451-b3b1-8b50d6afb5f1)
Even after waiting for several days, she still stand in the inn. Dunno if its bug in mod, engine or on my side.

**Comment by kurotatsu77** [comment]
I've done new run recently while making and debugging book quest, she did ran as she should for me... The only thing which was stopping her from doing it previously was navmesh issues, which were resolved a long time ago, no changes were made to it.
Maybe conflict with some mod which applies changes near the hub localtion?

**Comment by IHateMyKite** [comment]
Thanks, you were right, it was caused by navmesh conflict. And the source was Devious Pink mod. Placing the Unforgiving skyrim in load order after it solved the issue. Might be a good idea to think about moving the hub a little, so it will be in a different cell. That way there will be no conflict. Alternatively, some kind of patch will have to be created.

**Comment by kurotatsu77** [comment]
Oufffff, that's what I was afraid of... Do you have any suggestions for the revised location?
Another venue of approach could be waiting for naaitsab to release more or less complete version of DP and then either shift the house location or try to devise patch for it. Maybe add navmesh fix to the UD DP patch?

**Comment by IHateMyKite** [comment]
Moving the hub might be best idea, but issue is to find a place close unused cell close to whiterun. I think that moving it. After checking the esps for both mods, it looks like that the mods use for some reason more cells then needed. CK was most likely making some edits when it was not intended. Deleting the useless worldspase edits from both mods might solve the issue without making patch.
![map](https://github.com/kurotatsu77/UnforgivingSkyrim/assets/103142567/c6b52871-301b-4123-b3a4-0be4cc6383d3)
Green checks are cells edited by Devious Pink. Blue by Unforgiving Skyrim.
Either way I have also created the patch which solves the issue for me even if Devious Pink is loaded after US.
[USDPPatch.zip](https://github.com/kurotatsu77/UnforgivingSkyrim/files/11600354/USDPPatch.zip)

**Comment by kurotatsu77** [comment]
You, Sir, are awesome, without doubt.
Am I understanding it correctly that simply deleting some in US esp won't be enough, also in DP clean up needed?

**Comment by IHateMyKite** [comment]
Its possible, I tried running the xEdit clean up for DP, and it have removed some of the edited cells, as they are are just unused copies. Same goes for US. Cleaning both mods might make the mods compatible, but I'm not 100% sure.

**Comment by kurotatsu77** [comment]
Gotcha.
Then I will try to perform the clean-up in US esp for now. When DP gets released - I will try to contact naaitsab to propose him cleaning his esp too.

Any pointers on how to clean it up properly?

**Comment by IHateMyKite** [comment]
You can just clean it with xEdit. Latest version have the cleaning separated from main program. The executable is in same place and have to be run in same way as main executable. On LE, it is named TES5EditQuickAutoClean.exe. Once started, it will just let you choose mod to clean. That is all. Nothing groundbreaking.

**Comment by kurotatsu77** [comment]
OK, uploaded version which cleaned with xEdit, also there's some actions with Urag added, please have a look if you have some time.

**Comment by IHateMyKite** [comment]
Nice job, tried it and didn't found issue. One small nitpick might be to make the quest a little more unique, as currently most of them are only about eating black goo. Maybe the Urag can instead lock player in some unique abadon devices (there can only be flavor text about black goo, but player will technically not eat it)

**Comment by kurotatsu77** [comment]
Well, it's only a ruse for Urag to get his fix of bondage sex anyways, hehehe.
But I have couple of ideas to make other tests a little more different.
What kind of unique abadon devices you have in mind?

**Comment by IHateMyKite** [comment]
> Well, it's only a ruse for Urag to get his fix of bondage sex anyways, hehehe. But I have couple of ideas to make other tests a little more different. What kind of unique abadon devices you have in mind?

Dunno, it can be something connected to college or magick in general. Maybe the device will be unlocked only after player learns/study x amount of new spells. Or it can be very strong against magick to make it seem like device that is made agains mages. Or lastly, it can be some kind of device that have to be fed with soulgems for it to get weaker.

**Comment by kurotatsu77** [comment]
Well, all in all it's much better suited for some other quest, not tied to research share. I'm mulling over on some consensual non-con things maybe, custom devices would do good there.
Meanwhile completed all sharing, even made LL inject with abadon weapons after they are shown to Urag, he sells it to the people! :)
Please have a look once you have time and share your impressions.
